require("plugins.packer")

require("settings")
require("keymaps")
require("plugins.nvim-tree")
require("plugins.indent-blankline")
require("plugins.vista")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.nvim-treesitter")
require("plugins.alpha-nvim")
